export interface FounderBoxToolDefinition {
  name: string
  section: string
  phase: "v1" | "v2"
  description: string
  producesArtifacts?: boolean
}

export const FOUNDERBOX_TOOLS: FounderBoxToolDefinition[] = [
  { name: "founderbox_get_status", section: "Dashboard", phase: "v1", description: "Check FounderBox MCP health and account limits." },
  { name: "founderbox_list_tools", section: "Dashboard", phase: "v1", description: "List all available and planned FounderBox MCP tools." },
  { name: "accountability_get_today", section: "Accountability OS", phase: "v1", description: "Get today's revenue attempts, shipped outputs, proof, and logged work." },
  { name: "accountability_start_day", section: "Accountability OS", phase: "v1", description: "Create or update the morning check-in and daily targets." },
  { name: "accountability_log_outreach", section: "Accountability OS", phase: "v1", description: "Log an outreach attempt, follow-up, reply, proposal, or close." },
  { name: "accountability_log_work_session", section: "Accountability OS", phase: "v1", description: "Log a focused work session and output." },
  { name: "accountability_log_product_progress", section: "Accountability OS", phase: "v1", description: "Log product progress, stage, proof, blocker, and next action." },
  { name: "accountability_log_proof", section: "Accountability OS", phase: "v1", description: "Attach proof by URL or text to the operator's proof feed." },
  { name: "accountability_end_day_review", section: "Accountability OS", phase: "v1", description: "Create the end-of-day review." },
  { name: "accountability_get_weekly_report", section: "Accountability OS", phase: "v1", description: "Generate the weekly proof report." },
  { name: "accountability_list_flows", section: "Accountability OS", phase: "v1", description: "List installed accountability flows." },
  { name: "accountability_create_entry", section: "Accountability OS", phase: "v1", description: "Create an entry in a custom flow object." },
  { name: "accountability_query_metrics", section: "Accountability OS", phase: "v1", description: "Query revenue attempts, shipped outputs, deep work, and method stats." },
  { name: "accountability_create_share_report", section: "Accountability OS", phase: "v1", description: "Create a shareable weekly proof report." },
  { name: "resume_list_templates", section: "Resume Forge", phase: "v1", description: "List available resume templates." },
  { name: "resume_generate", section: "Resume Forge", phase: "v1", description: "Generate a role-focused resume draft." },
  { name: "resume_optimize_for_job", section: "Resume Forge", phase: "v1", description: "Tailor resume content to a job description." },
  { name: "resume_score_ats", section: "Resume Forge", phase: "v1", description: "Score resume content for ATS fit." },
  { name: "resume_render_pdf", section: "Resume Forge", phase: "v1", description: "Render a resume PDF artifact.", producesArtifacts: true },
  { name: "proposal_list_industries", section: "Proposal Generator", phase: "v1", description: "List supported proposal industries." },
  { name: "proposal_get_template", section: "Proposal Generator", phase: "v1", description: "Get an industry proposal template." },
  { name: "proposal_generate", section: "Proposal Generator", phase: "v1", description: "Generate a complete client proposal from a brief." },
  { name: "proposal_estimate_pricing", section: "Proposal Generator", phase: "v1", description: "Estimate proposal pricing packages." },
  { name: "proposal_render_pdf", section: "Proposal Generator", phase: "v1", description: "Render a proposal PDF artifact.", producesArtifacts: true },
  { name: "proposal_bulk_generate", section: "Proposal Generator", phase: "v1", description: "Generate up to 10 proposals from client briefs." },
  { name: "startup_lens_get_layers", section: "Startup Lens", phase: "v1", description: "Return the Startup Lens analysis framework." },
  { name: "startup_lens_create_framework", section: "Startup Lens", phase: "v1", description: "Create a blank Startup Lens framework for a startup." },
  { name: "startup_lens_analyze_notes", section: "Startup Lens", phase: "v1", description: "Analyze notes against the Startup Lens framework." },
  { name: "startup_lens_generate_report", section: "Startup Lens", phase: "v1", description: "Generate a structured Startup Lens report." },
  { name: "startup_lens_render_pdf", section: "Startup Lens", phase: "v1", description: "Render a Startup Lens PDF artifact.", producesArtifacts: true },
  { name: "launchpath_get_stage_map", section: "Launchpath Atlas", phase: "v2", description: "Return founder stage map." },
  { name: "launchpath_recommend_stage", section: "Launchpath Atlas", phase: "v2", description: "Recommend founder stage from context." },
  { name: "launchpath_create_weekly_plan", section: "Launchpath Atlas", phase: "v2", description: "Create a weekly founder action plan." },
  { name: "launchpath_get_resources", section: "Launchpath Atlas", phase: "v2", description: "Return curated founder resources." },
  { name: "cold_email_list_industries", section: "Cold Emails", phase: "v2", description: "List cold email industries and use cases." },
  { name: "cold_email_generate", section: "Cold Emails", phase: "v2", description: "Generate a cold email." },
  { name: "cold_email_generate_sequence", section: "Cold Emails", phase: "v2", description: "Generate a multi-step email sequence." },
  { name: "cold_email_personalize", section: "Cold Emails", phase: "v2", description: "Personalize cold email copy." },
  { name: "cold_email_calculate_outreach_volume", section: "Cold Emails", phase: "v2", description: "Calculate outreach volume." },
  { name: "competitive_create_brief", section: "Competitive Analysis", phase: "v2", description: "Create a competitor brief." },
  { name: "competitive_compare_companies", section: "Competitive Analysis", phase: "v2", description: "Compare competitors." },
  { name: "competitive_generate_swot", section: "Competitive Analysis", phase: "v2", description: "Generate a SWOT analysis." },
  { name: "competitive_generate_positioning_map", section: "Competitive Analysis", phase: "v2", description: "Generate positioning map data." },
  { name: "contract_list_templates", section: "Contracts", phase: "v2", description: "List contract templates." },
  { name: "contract_get_template_fields", section: "Contracts", phase: "v2", description: "Get contract template fields." },
  { name: "contract_generate", section: "Contracts", phase: "v2", description: "Generate a contract draft." },
  { name: "contract_add_clauses", section: "Contracts", phase: "v2", description: "Add standard clauses." },
  { name: "contract_render_pdf", section: "Contracts", phase: "v2", description: "Render contract PDF.", producesArtifacts: true },
  { name: "invoice_create", section: "Invoices", phase: "v2", description: "Create an invoice." },
  { name: "invoice_calculate_totals", section: "Invoices", phase: "v2", description: "Calculate invoice totals." },
  { name: "invoice_apply_tax_region", section: "Invoices", phase: "v2", description: "Apply tax region settings." },
  { name: "invoice_render_pdf", section: "Invoices", phase: "v2", description: "Render invoice PDF.", producesArtifacts: true },
  { name: "seo_generate_audit_plan", section: "SEO Content", phase: "v2", description: "Generate SEO audit plan." },
  { name: "seo_create_keyword_brief", section: "SEO Content", phase: "v2", description: "Create keyword brief." },
  { name: "seo_generate_content_plan", section: "SEO Content", phase: "v2", description: "Generate SEO content plan." },
  { name: "seo_calculate_roi_projection", section: "SEO Content", phase: "v2", description: "Calculate SEO ROI projection." },
  { name: "sales_generate_sdr_plan", section: "Sales Copy", phase: "v2", description: "Generate an SDR plan." },
  { name: "sales_generate_script", section: "Sales Copy", phase: "v2", description: "Generate sales scripts." },
  { name: "sales_score_leads", section: "Sales Copy", phase: "v2", description: "Score leads." },
  { name: "sales_generate_followup_sequence", section: "Sales Copy", phase: "v2", description: "Generate follow-up sequence." },
  { name: "sales_pipeline_summary", section: "Sales Copy", phase: "v2", description: "Summarize pipeline data." },
  { name: "social_generate_strategy", section: "Social Media", phase: "v2", description: "Generate social strategy." },
  { name: "social_generate_content_calendar", section: "Social Media", phase: "v2", description: "Generate content calendar." },
  { name: "social_generate_post_ideas", section: "Social Media", phase: "v2", description: "Generate post ideas." },
  { name: "social_generate_hashtags", section: "Social Media", phase: "v2", description: "Generate hashtags." },
  { name: "social_generate_crisis_plan", section: "Social Media", phase: "v2", description: "Generate crisis plan." },
  { name: "founderbox_get_account_usage", section: "Dashboard", phase: "v2", description: "Get account usage." },
  { name: "founderbox_list_artifacts", section: "Dashboard", phase: "v2", description: "List generated artifacts." },
  { name: "founderbox_get_artifact", section: "Dashboard", phase: "v2", description: "Get an artifact." },
  { name: "founderbox_list_available_skills", section: "Dashboard", phase: "v2", description: "List FounderBox AI skills." },
]

export const FOUNDERBOX_SKILLS = [
  "founderbox-resume-creator",
  "founderbox-proposal-writer",
  "founderbox-startup-lens-analyst",
  "founderbox-launchpath-coach",
  "founderbox-cold-outreach",
  "founderbox-competitive-analyst",
  "founderbox-contract-drafter",
  "founderbox-invoice-operator",
  "founderbox-seo-strategist",
  "founderbox-sales-operator",
  "founderbox-social-growth",
  "founderbox-developer",
  "founderbox-accountability-coach",
  "founderbox-solo-dev-operator",
  "founderbox-agency-owner-operator",
  "founderbox-freelancer-operator",
  "founderbox-outreach-analyst",
  "founderbox-weekly-review",
]
