import { notFound } from "next/navigation"
import { headers } from "next/headers"
import { hashIp } from "@/lib/audit"
import { prisma } from "@/lib/prisma"
import { StatCard } from "@/components/ui/stat-card"

interface ReportMetrics {
  revenueAttempts?: { total?: number }
  shippedOutputs?: { total?: number }
  deepWorkMinutes?: number
}

export default async function SharePage(context: { params: Promise<{ token: string }> }) {
  const { token } = await context.params
  const headerStore = await headers()
  const shareLink = await prisma.shareLink.findUnique({
    where: { token },
    include: { weeklyReview: true, workspace: true },
  })

  if (!shareLink || shareLink.revokedAt || (shareLink.expiresAt && shareLink.expiresAt < new Date())) notFound()

  await prisma.$transaction([
    prisma.shareLink.update({ where: { id: shareLink.id }, data: { viewCount: { increment: 1 }, lastViewedAt: new Date() } }),
    prisma.shareLinkView.create({
      data: {
        shareLinkId: shareLink.id,
        ipHash: hashIp(headerStore.get("x-forwarded-for")?.split(",")[0]?.trim() || headerStore.get("x-real-ip")),
        userAgent: headerStore.get("user-agent") || undefined,
        referrer: headerStore.get("referer") || undefined,
      },
    }),
  ])

  const metrics = (shareLink.weeklyReview?.metrics as ReportMetrics | null) || {}

  return (
    <main className="min-h-screen bg-[#111118] px-6 py-12 text-[#EDE9DC]">
      <article className="mx-auto max-w-3xl">
        <header className="border-b border-border pb-8">
          <p className="studio-label mb-3">FounderBox Proof Report</p>
          <h1 className="text-3xl font-extrabold leading-tight">{shareLink.title}</h1>
          <p className="mt-2 text-sm text-[#9E9880]">{shareLink.workspace.name}</p>
        </header>

        {(metrics.revenueAttempts || metrics.shippedOutputs || metrics.deepWorkMinutes != null) && (
          <div className="mt-8 grid grid-cols-3 gap-3">
            <StatCard label="Revenue Attempts" value={metrics.revenueAttempts?.total ?? 0} accent />
            <StatCard label="Shipped Outputs" value={metrics.shippedOutputs?.total ?? 0} />
            <StatCard label="Deep Work" value={`${Math.round((metrics.deepWorkMinutes ?? 0) / 60)}h`} />
          </div>
        )}

        <pre className="mt-8 whitespace-pre-wrap rounded-lg border border-border bg-[#18181F] p-6 text-sm leading-7 text-[#C9C3B0]">
          {shareLink.weeklyReview?.markdown || "No report content."}
        </pre>

        <footer className="mt-10 flex items-center justify-between border-t border-border pt-6 text-xs text-[#9E9880]">
          <span>
            Verified proof, generated by{" "}
            <a href="https://founderbox.loopxo.org" className="font-semibold text-[#D4A853] hover:underline">FounderBox</a>
          </span>
          <span>{shareLink.redacted ? "Redacted view" : "Full view"}</span>
        </footer>
      </article>
    </main>
  )
}
